version: '2'

services:

  web:
    build:
      context: .docker/nginx
    volumes:
    - ./:/var/www
    ports:
    - "8080:80"
    depends_on:
      - app

  workers:
    build:
      context: .docker/php-worker
      args:
        PUID: "1000"
        PHP_INSTALL_XDEBUG: "true"
        INSTALL_GIT: "true"
        PHP_XDEBUG_PORT: "9000"
    volumes:
      - ./:/var/www
    environment:
      - "PHP_IDE_CONFIG=serverName=localhost"
    user: www-data
    depends_on:
      - redis
      - rabbit1

  app:
    build:
      context: .docker/php
      args:
        PUID: "1000"
        PHP_INSTALL_XDEBUG: "true"
        INSTALL_GIT: "true"
        PHP_XDEBUG_PORT: "9000"
    volumes:
    - ./:/var/www
    environment:
    - "POSTGRES_HOST=database"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=postgres"
    - "POSTGRES_DB=example"
    - "PHP_IDE_CONFIG=serverName=localhost"
    user: www-data
    depends_on:
      - redis
      - rabbit1

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/data/redis-data:/data

  rabbit1:
    build:
      context: .docker/rabbit
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

